[build]
  functions = "backend/functions"
  publish = "backend/public"

[dev]
  functions = "backend/functions"
  publish = "backend/public"
  autoLaunch = false

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
